name: shawky
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+5

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.1.2
  permission_handler: ^11.3.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  get_it: ^7.7.0
  privacy_screen: ^0.0.6
  local_auth: ^2.2.0
  url_launcher: ^6.3.0
  fluttertoast: ^8.2.6
  percent_indicator: ^4.2.3
  dropdown_search: ^5.0.6
  fl_chart: ^0.68.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  qr_flutter: ^4.1.0
  intl: ^0.19.0
#  firebase_core: ^2.29.0
#  cloud_firestore: ^4.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/background.png"
  image_path_ios: "assets/images/background.png"
  min_sdk_android: 22
  adaptive_icon_background: "#232323"



flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/money/
    - assets/images/profiles/
    - assets/json/
